version: "3.9"

services:
  app:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - db
    volumes:
      - ./Backend:/app    # Mount your backend code for live reload
    command: ["python", "server.py","config.prd.ini"]

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5432:5432"