version: "3.9"

services:
  app:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - db
    volumes:
      - ./Backend:/app    # Mount your backend code for live reload
    command: ["python", "server.py","config.prd.ini"]

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./Frontend:/app
      - node_modules:/app/node_modules
    command: ["npm", "run", "dev"]

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: nutrition
      POSTGRES_USER: klaid
      POSTGRES_PASSWORD: KLAID99100
    ports:
      - "5432:5432"

volumes:
  node_modules: